#!/bin/sh
set -ex

# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Run on the host

# Dependencies:
#   ca-certificates and curl packages: when you run this script
#   ca-certificates: on the user's target system since HTTPS is used

# Inputs:
#   DEBUSINE_HOST
#   DEBUSINE_SCOPE
#   DEBUSINE_USER
#   DEBUSINE_TOKEN
#   DEBUSINE_WORKSPACE
#   DEBUSINE_WORKFLOW_ID
#   DEBUSINE_TARGET_WORKSPACE
#   SRCPKG_NAME
#   SRCPKG_VERSION
#   SUITE
#   BUILD_RESULT (success|failure|cancelled)

# Outputs:
#   $GITHUB_STEP_SUMMARY: summary output for the web UI

: ${GITHUB_STEP_SUMMARY:=/dev/null}

. "$(dirname "$0")/sources-common.sh"

if [ "${BUILD_RESULT}" = "success" ]; then
    build_status="successful"
else
    build_status="failed"
fi

if [ "${BUILD_RESULT}" = "success" ]; then
    target_sources=$(emit_sources "${DEBUSINE_TARGET_WORKSPACE}")
    ci_sources=$(emit_sources "${DEBUSINE_WORKSPACE}")
fi

cat > "$GITHUB_STEP_SUMMARY" <<END2
**Build of $SRCPKG_NAME (\`$SRCPKG_VERSION\`) ${build_status}.**

# Debusine workspace

Build logs and artifacts are available directly from https://${DEBUSINE_HOST}/${DEBUSINE_SCOPE}/${DEBUSINE_WORKSPACE}/work-request/${DEBUSINE_WORKFLOW_ID}/ (SSO login required).
END2

if [ "${BUILD_RESULT}" = "success" ]; then
    cat >> "$GITHUB_STEP_SUMMARY" <<END2

# apt access

Get an API token by logging in to https://${DEBUSINE_HOST}/ and then go to "Tokens" from your username on the top right. Adjust \`debusine-ci-auth.conf\` below to incorporate your Debusine username and API token. Your Debusine username should look like an email address as used with SSO. You can check against the displayed username on the top right when you are logged in.

## Create \`debusine-ci-auth.conf\`
\`\`\`
sudo sh -c 'umask 077; cat > /etc/apt/auth.conf.d/debusine-ci-auth.conf' <<END
machine deb.${DEBUSINE_HOST}
login <debusine account email>
password <API token>
END
\`\`\`

## Create \`${DEBUSINE_TARGET_WORKSPACE}.sources\` for baseline apt repository access
\`\`\`
sudo sh -c 'cat > /etc/apt/sources.list.d/${DEBUSINE_TARGET_WORKSPACE}.sources' <<END
${target_sources}
END
\`\`\`

## Create \`qli-ci.sources\` for build-specific apt repository access
\`\`\`
sudo sh -c 'cat > /etc/apt/sources.list.d/qli-ci.sources' <<END
${ci_sources}
END
\`\`\`
END2
fi
